base_config: 
  - egs/egs_bases/tts/fs2.yaml
  - modules/ProDiff/config/base.yaml

raw_data_dir: 'data/TiuTiu/raw'
processed_data_dir: 'data/TiuTiu/processed'
binary_data_dir: 'data/TiuTiu/binary'

task_cls: modules.ProDiff.task.ProDiff_teacher_task.ProDiff_teacher_Task

preprocess_args:
  forced_align: mfa
  add_eos_bos: false

binarizer_cls: egs.datasets.audio.tiutiu.binarizer.AcousticBinarizer
test_num: 100
valid_num: 100
num_spk: 1
reset_phone_dict: false

# FastDiff vocoder
vocoder: fastdiff
N: 4 # denoising steps
vocoder_ckpt: checkpoints/FastDiff

audio_sample_rate: 44100
audio_num_mel_bins: 128
hop_size: 512            # Hop size.
fft_size: 2048           # FFT size.
win_size: 2048           # FFT size.
fmin: 40
fmax: 16000

# diffusion
timesteps: 4
timescale: 1
schedule_type: 'vpsde'


