base_config:
  - ./base.yaml

raw_data_dir: 'data/LJSpeech/raw'
processed_data_dir: 'data/LJSpeech/processed'
binary_data_dir: 'data/LJSpeech/binary'

task_cls: modules.ProDiff.task.ProDiff_teacher_task.ProDiff_teacher_Task

# diffusion
timesteps: 4
timescale: 1
schedule_type: 'vpsde'
