base_config:
  - ./base.yaml

raw_data_dir: 'data/LJSpeech/raw'
processed_data_dir: 'data/LJSpeech/processed'
binary_data_dir: 'data/LJSpeech/binary'

task_cls: modules.ProDiff.task.ProDiff_task.ProDiff_Task


# diffusion
timesteps: 4
teacher_ckpt: checkpoints/ProDiff_Teacher/model_ckpt_steps_188000.ckpt
# diff_decoder_type: 'wavenet'
schedule_type: 'vpsde'

