base_config: "handler/base_config.yaml"

#############
# dataset
#############
datasets:
  - data_dir : data/opcp
    speaker: opcp
    language: zh
num_spk: 1
data_dir: data/binary_opcp
test_num: 6
valid_num: 6

#############
# model option
#############
use_spk_id: true
use_lang_id: true
use_dur_embed: true
use_pitch_embed: true
use_voicing_embed: false
use_breath_embed: false