from component.inferer.dur_predictor import DurPredictorInferer
from component.inferer.pitch_predictor import PitchPredictorInferer
from component.inferer.vari_predictor import BreathPredictorInferer, VoicingPredictorInferer
from component.inferer.base import get_inferer_cls