from component.inferer.prodiff_teacher import ProDiffTeacherInferrer
from component.inferer.dur_predictor import DurPredictorInferer
from component.inferer.pitch_predictor import PitchPredictorInferer
from component.inferer.base import get_inferer_cls